-- Habilita la creaciÃ³n de usuarios en Oracle 12c/19c/21c/23c
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- Crear el usuario
CREATE USER usuario IDENTIFIED BY "123456"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- Asignar cuota y permisos bÃ¡sicos
ALTER USER usuario QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION TO usuario;
GRANT "RESOURCE" TO usuario;
ALTER USER usuario DEFAULT ROLE "RESOURCE";