/* Funcion que permita calcular lo total vendido por un empleado en un rango de un mes */
CREATE OR REPLACE FUNCTION F_CALCULAR_TOTAL_VENDIDO_EMPLEADO_POR_MES(
    P_RUT_EMPLEADO varchar2,
    P_MES NUMBER,
    P_ANIO NUMBER
)RETURN varchar2 IS
    V_NOMBRE_COMPLETO varchar2(50);
    V_TOTAL_VENDIDO NUMBER(10);
BEGIN
    SELECT
        (
            E.PRIMER_NOMBRE||' '||E.SEGUNDO_NOMBRE||' '||
            E.PRIMER_APELLIDO||' '||E.SEGUNDO_APELLIDO
        ),
        SUM(V.TOTAL)
    INTO V_NOMBRE_COMPLETO, V_TOTAL_VENDIDO
    FROM VENTA V 
    INNER JOIN EMPLEADO E ON V.ID_EMPLEADO=E.ID_EMPLEADO
    WHERE   extract(YEAR FROM V.FECHA_VENTA)=P_ANIO
        AND extract(MONTH FROM V.FECHA_VENTA)=P_MES
        AND E.RUT = P_RUT_EMPLEADO
    GROUP BY (
            E.PRIMER_NOMBRE||' '||E.SEGUNDO_NOMBRE||' '||
            E.PRIMER_APELLIDO||' '||E.SEGUNDO_APELLIDO
        );

    RETURN V_NOMBRE_COMPLETO||': $'||V_TOTAL_VENDIDO;
EXCEPTION when NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('RUT INEXISTENTE');
END F_CALCULAR_TOTAL_VENDIDO_EMPLEADO_POR_MES;
/
commit;
/
/* =================================PRUEBAS================================== */

SELECT F_CALCULAR_TOTAL_VENDIDO_EMPLEADO_POR_MES('33.938.240-9', 2, 2026) AS RESULTADO FROM DUAL;

/* DATOS DE JEREMI: ('33.938.240-9', 2, 2026) */