-- Generado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
-- Adaptado con PKs, Identity Columns y FKs integradas inline en CREATE TABLE

DROP TABLE ANEXO_CONTRATO CASCADE CONSTRAINTS;
DROP TABLE CALLE CASCADE CONSTRAINTS;
DROP TABLE CARGO CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA_EVENTO CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE CIUDAD CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE CONTRATO CASCADE CONSTRAINTS;
DROP TABLE EDITORIAL CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE EVENTO CASCADE CONSTRAINTS;
DROP TABLE IDIOMA CASCADE CONSTRAINTS;
DROP TABLE INSCRIPCION CASCADE CONSTRAINTS;
DROP TABLE LOCALIDAD CASCADE CONSTRAINTS;
DROP TABLE MARCA CASCADE CONSTRAINTS;
DROP TABLE METODO_PAGO CASCADE CONSTRAINTS;
DROP TABLE PAGO CASCADE CONSTRAINTS;
DROP TABLE PAIS CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE N_N_VENTA_PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE REVIEW CASCADE CONSTRAINTS;
DROP TABLE STOCK CASCADE CONSTRAINTS;
DROP TABLE SUCURSAL CASCADE CONSTRAINTS;
DROP TABLE TIPO_EVENTO CASCADE CONSTRAINTS;
DROP TABLE TIPO_REVIEW CASCADE CONSTRAINTS;
DROP TABLE VENTA CASCADE CONSTRAINTS;

-- 1. TABLAS INDEPENDIENTES (SIN FKs)

CREATE TABLE PAIS 
    ( 
     id     NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PAIS_PK PRIMARY KEY, 
     nombre VARCHAR2 (50 CHAR) NOT NULL 
    ) 
;

CREATE TABLE CARGO 
    ( 
     id          NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT CARGO_PK PRIMARY KEY, 
     nombre      VARCHAR2 (40 CHAR) NOT NULL, 
     descripción VARCHAR2 (500 CHAR) NOT NULL 
    ) 
;

CREATE TABLE CATEGORIA_EVENTO 
    ( 
     id          NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT CATEGORIA_EVENTO_PK PRIMARY KEY, 
     nombre      VARCHAR2 (50 CHAR) NOT NULL, 
     descripción VARCHAR2 (100 CHAR) 
    ) 
;

CREATE TABLE CATEGORIA_PRODUCTO 
    ( 
     id          NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT CATEGORIA_PRODUCTO_PK PRIMARY KEY, 
     nombre      VARCHAR2 (30 CHAR) NOT NULL, 
     descripcion VARCHAR2 (300 CHAR) 
    ) 
;

CREATE TABLE CLIENTE 
    ( 
     id               NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT CLIENTE_PK PRIMARY KEY, 
     primer_nombre    VARCHAR2 (30 CHAR) NOT NULL, 
     segundo_nombre   VARCHAR2 (30 CHAR), 
     primer_apellido  VARCHAR2 (30 CHAR) NOT NULL, 
     segundo_apellido VARCHAR2 (30 CHAR), 
     rut              VARCHAR2 (10 CHAR) NOT NULL, 
     email            VARCHAR2 (50 CHAR), 
     telefono         VARCHAR2 (20 CHAR) 
    ) 
;

CREATE TABLE EDITORIAL 
    ( 
     id       NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT EDITORIAL_PK PRIMARY KEY, 
     nombre   VARCHAR2 (40 CHAR) NOT NULL, 
     telefono VARCHAR2 (20 CHAR) NOT NULL, 
     email    VARCHAR2 (30 CHAR) NOT NULL 
    ) 
;

CREATE TABLE IDIOMA 
    ( 
     id     NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT IDIOMA_PK PRIMARY KEY, 
     nombre VARCHAR2 (20) NOT NULL 
    ) 
;

CREATE TABLE MARCA 
    ( 
     id       NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT MARCA_PK PRIMARY KEY, 
     nombre   VARCHAR2 (50 CHAR) NOT NULL, 
     telefono VARCHAR2 (20 CHAR) NOT NULL, 
     email    VARCHAR2 (30 CHAR) NOT NULL 
    ) 
;

CREATE TABLE METODO_PAGO 
    ( 
     id     NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT METODO_PAGO_PK PRIMARY KEY, 
     nombre VARCHAR2 (30 CHAR) NOT NULL 
    ) 
;

CREATE TABLE PROVEEDOR 
    ( 
     id       NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PROVEEDOR_PK PRIMARY KEY, 
     nombre   VARCHAR2 (30) NOT NULL, 
     telefono VARCHAR2 (30 CHAR) NOT NULL, 
     email    VARCHAR2 (30 CHAR) NOT NULL 
    ) 
;

CREATE TABLE TIPO_REVIEW 
    ( 
     id          NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT TIPO_REVIEW_PK PRIMARY KEY, 
     nombre      VARCHAR2 (30 CHAR) NOT NULL, 
     descripción VARCHAR2 (50 CHAR) NOT NULL 
    ) 
;

-- 2. TABLAS DE PRIMER NIVEL DE DEPENDENCIA

CREATE TABLE REGION 
    ( 
     id      NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT REGION_PK PRIMARY KEY, 
     nombre  VARCHAR2 (100 CHAR) NOT NULL, 
     PAIS_id NUMBER NOT NULL CONSTRAINT REGION_PAIS_FK REFERENCES PAIS(id)
    ) 
;

CREATE TABLE REVIEW 
    ( 
     id             NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT REVIEW_PK PRIMARY KEY, 
     titulo         VARCHAR2 (40 CHAR), 
     mensaje        VARCHAR2 (500 CHAR) NOT NULL, 
     TIPO_REVIEW_id NUMBER NOT NULL CONSTRAINT REVIEW_TIPO_REVIEW_FK REFERENCES TIPO_REVIEW(id), 
     CLIENTE_id     NUMBER NOT NULL CONSTRAINT REVIEW_CLIENTE_FK REFERENCES CLIENTE(id)
    ) 
;

CREATE TABLE TIPO_EVENTO 
    ( 
     id                  NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT TIPO_EVENTO_PK PRIMARY KEY, 
     nombre              VARCHAR2 (100 CHAR) NOT NULL, 
     inicio_evento       TIMESTAMP NOT NULL, 
     final_evento        TIMESTAMP NOT NULL, 
     cupo_maximo         NUMBER (4), 
     descripcion         VARCHAR2 (500 CHAR), 
     CATEGORIA_EVENTO_id NUMBER NOT NULL CONSTRAINT TIPO_EVENTO_CATEGORIA_EVENTO_FK REFERENCES CATEGORIA_EVENTO(id)
    ) 
;

CREATE TABLE PRODUCTO 
    ( 
     id                    NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PRODUCTO_PK PRIMARY KEY, 
     sku                   VARCHAR2 (30 CHAR) NOT NULL, 
     nombre_producto       VARCHAR2 (100 CHAR) NOT NULL, 
     precio                NUMBER (7) NOT NULL, 
     min_jugadores         NUMBER (2), 
     max_jugadores         NUMBER (2), 
     descripción           VARCHAR2 (500 CHAR), 
     EDITORIAL_id          NUMBER NOT NULL CONSTRAINT PRODUCTO_EDITORIAL_FK REFERENCES EDITORIAL(id), 
     MARCA_id              NUMBER NOT NULL CONSTRAINT PRODUCTO_MARCA_FK REFERENCES MARCA(id), 
     IDIOMA_id             NUMBER NOT NULL CONSTRAINT PRODUCTO_IDIOMA_FK REFERENCES IDIOMA(id), 
     CATEGORIA_PRODUCTO_id NUMBER NOT NULL CONSTRAINT PRODUCTO_CATEGORIA_PRODUCTO_FK REFERENCES CATEGORIA_PRODUCTO(id), 
     PROVEEDOR_id          NUMBER NOT NULL CONSTRAINT PRODUCTO_PROVEEDOR_FK REFERENCES PROVEEDOR(id)
    ) 
;

-- 3. TABLAS DE SEGUNDO NIVEL DE DEPENDENCIA

CREATE TABLE CIUDAD 
    ( 
     id        NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT CIUDAD_PK PRIMARY KEY, 
     nombre    VARCHAR2 (100 CHAR) NOT NULL, 
     REGION_id NUMBER NOT NULL CONSTRAINT CIUDAD_REGION_FK REFERENCES REGION(id)
    ) 
;

CREATE TABLE LOCALIDAD 
    ( 
     id        NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT LOCALIDAD_PK PRIMARY KEY, 
     nombre    VARCHAR2 (100 CHAR) NOT NULL, 
     REGION_id NUMBER NOT NULL CONSTRAINT LOCALIDAD_REGION_FK REFERENCES REGION(id)
    ) 
;

-- 4. TABLAS DE TERCER NIVEL DE DEPENDENCIA

CREATE TABLE CALLE 
    ( 
     id           NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT CALLE_PK PRIMARY KEY, 
     nombre       VARCHAR2 (100 CHAR) NOT NULL, 
     CIUDAD_id    NUMBER NOT NULL CONSTRAINT CALLE_CIUDAD_FK REFERENCES CIUDAD(id), 
     LOCALIDAD_id NUMBER NOT NULL CONSTRAINT CALLE_LOCALIDAD_FK REFERENCES LOCALIDAD(id)
    ) 
;

-- 5. SUCURSAL Y DEPENDIENTES DIRECTOS

CREATE TABLE SUCURSAL 
    ( 
     id              NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT SUCURSAL_PK PRIMARY KEY, 
     nombre          VARCHAR2 (100 CHAR) NOT NULL, 
     numero_contacto VARCHAR2 (20 CHAR) NOT NULL, 
     email_contacto  VARCHAR2 (50 CHAR) NOT NULL, 
     hora_apertura   TIMESTAMP NOT NULL, 
     hora_cierre     TIMESTAMP NOT NULL, 
     CALLE_id        NUMBER NOT NULL CONSTRAINT SUCURSAL_CALLE_FK REFERENCES CALLE(id)
    ) 
;

CREATE TABLE EMPLEADO 
    ( 
     id               NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT EMPLEADO_PK PRIMARY KEY, 
     primer_nombre    VARCHAR2 (30 CHAR) NOT NULL, 
     segundo_nombre   VARCHAR2 (30 CHAR), 
     primer_apellido  VARCHAR2 (30 CHAR) NOT NULL, 
     segundo_apellido VARCHAR2 (30 CHAR), 
     CARGO_id         NUMBER NOT NULL CONSTRAINT EMPLEADO_CARGO_FK REFERENCES CARGO(id), 
     SUCURSAL_id      NUMBER NOT NULL CONSTRAINT EMPLEADO_SUCURSAL_FK REFERENCES SUCURSAL(id)
    ) 
;

CREATE TABLE EVENTO 
    ( 
     id             NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT EVENTO_PK PRIMARY KEY, 
     nombre         VARCHAR2 (50 CHAR) NOT NULL, 
     descripcion    VARCHAR2 (300 CHAR) NOT NULL, 
     TIPO_EVENTO_id NUMBER NOT NULL CONSTRAINT EVENTO_TIPO_EVENTO_FK REFERENCES TIPO_EVENTO(id), 
     SUCURSAL_id    NUMBER NOT NULL CONSTRAINT EVENTO_SUCURSAL_FK REFERENCES SUCURSAL(id)
    ) 
;

CREATE TABLE STOCK 
    ( 
     id               NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT STOCK_PK PRIMARY KEY, 
     stock_disponible NUMBER (6) NOT NULL, 
     stock_minimo     NUMBER (3) NOT NULL, 
     SUCURSAL_id      NUMBER NOT NULL CONSTRAINT STOCK_SUCURSAL_FK REFERENCES SUCURSAL(id), 
     PRODUCTO_id      NUMBER NOT NULL CONSTRAINT STOCK_PRODUCTO_FK REFERENCES PRODUCTO(id)
    ) 
;

CREATE TABLE VENTA 
    ( 
     id             NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT VENTA_PK PRIMARY KEY, 
     fecha_venta    DATE NOT NULL, 
     total          NUMBER (15) NOT NULL, 
     nro_boleta     VARCHAR2 (20), 
     SUCURSAL_id    NUMBER NOT NULL CONSTRAINT VENTA_SUCURSAL_FK REFERENCES SUCURSAL(id), 
     CLIENTE_id     NUMBER NOT NULL CONSTRAINT VENTA_CLIENTE_FK REFERENCES CLIENTE(id), 
     METODO_PAGO_id NUMBER NOT NULL CONSTRAINT VENTA_METODO_PAGO_FK REFERENCES METODO_PAGO(id)
    ) 
;

-- 6. TABLAS FINALES DE MAYOR PROFUNDIDAD EN LA JERARQUÍA

CREATE TABLE CONTRATO 
    ( 
     id              NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT CONTRATO_PK PRIMARY KEY, 
     inicio_contrato TIMESTAMP NOT NULL, 
     fin_contrato    TIMESTAMP, 
     EMPLEADO_id     NUMBER NOT NULL CONSTRAINT CONTRATO_EMPLEADO_FK REFERENCES EMPLEADO(id)
    ) 
;

CREATE TABLE ANEXO_CONTRATO 
    ( 
     id          NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT ANEXO_CONTRATO_PK PRIMARY KEY, 
     CONTRATO_id NUMBER NOT NULL CONSTRAINT ANEXO_CONTRATO_CONTRATO_FK REFERENCES CONTRATO(id)
    ) 
;

CREATE TABLE INSCRIPCION 
    ( 
     id                NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT INSCRIPCION_PK PRIMARY KEY, 
     fecha_inscripcion TIMESTAMP NOT NULL, 
     asistio           VARCHAR2 (1 CHAR) NOT NULL, 
     EVENTO_id         NUMBER NOT NULL CONSTRAINT INSCRIPCION_EVENTO_FK REFERENCES EVENTO(id)
    ) 
;

CREATE TABLE PAGO 
    ( 
     id                 NUMBER GENERATED ALWAYS AS IDENTITY CONSTRAINT PAGO_PK PRIMARY KEY, 
     cantidad           NUMBER (4) NOT NULL, 
     precio_unitario    NUMBER (7) NOT NULL, 
     descuento_aplicado NUMBER (3), 
     VENTA_id           NUMBER NOT NULL CONSTRAINT PAGO_VENTA_FK REFERENCES VENTA(id)
    ) 
;

CREATE TABLE N_N_VENTA_PRODUCTO 
    ( 
     VENTA_id    NUMBER NOT NULL CONSTRAINT N_N_VENTA_PRODUCTO_VENTA_FK REFERENCES VENTA(id), 
     PRODUCTO_id NUMBER NOT NULL CONSTRAINT N_N_VENTA_PRODUCTO_PRODUCTO_FK REFERENCES PRODUCTO(id),
     CONSTRAINT N_N_VENTA_PRODUCTO_PK PRIMARY KEY ( VENTA_id, PRODUCTO_id )
    ) 
;